package za.co.shilton.vasorderj23.common.statemachine.state;

public enum Event {

    ORDER_VALIDATION_PASSED,
    ORDER_VALIDATION_FAILED,
    QUOTE_VALIDATION_PASSED,
    QUOTE_VALIDATION_FAILED,
    LIMIT_VALIDATION_PASSED,
    LIMIT_VALIDATION_FAILED,
    PAYMENT_PASSED,
    PAYMENT_FAILED,
    PARTNER_ORDER_PASSED,
    PARTNER_ORDER_FAILED,
    HISTORY_UPDATED,
    HISTORY_FAILED,
    NOTIFICATION_PASSED,
    NOTIFICATION_FAILED,
    ORDER_PASSED,
    ORDER_FAILED,

}
